## drupal:9
## postgres:14
## Drupal which is a content management platform
version: "2.21"
services:
  drupal:
    image: drupal:9
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/theme

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=drupal
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

volumes:
  drupal-profiles:
  drupal-sites:
  drupal-modules:
  drupal-themes: